name: Publish
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      env:
        USE_SSH: true
        GIT_USER: git
    - run: npm install
    - run: git config --global user.email "actions@github.com" && git config --global user.name "gh-actions"
    - run: npm run build
    - run: rm -v !("build"|".git") && mv build/* . && rm -r build
    - run: git add . && git commit "Publish" && git push --force -u origin gh-pages
